### ISSUE TITLE
charJob is Undefined

### ISSUE THREAD

**Issue by morojgovany** [VORPCORE/vorp_crafting#30]
Hi,
I have a problem with the app,js:238 file on the variable charJob, how do you define this one ? charJob is always undefined because no call is made on server side to retrieve it.
Log : `CrBrowserMain/ Uncaught ReferenceError: charJob is not defined (@vorp_crafting/ui/app.js:238)`
I put this job config for a category : `{"butcher"}`.
Did I miss something ?
Thx

Relates PR #29

**Comment by CrimsonFreak** [comment]
I will fix the error, but it won't solve your problem. It is very likely that you character just doesn't have a job. charJob doesn't have to be called from the server, it' a variable in the UI standing for character.job.
Anyway, fixing now

**Comment by CrimsonFreak** [comment]
Ok, PR #31 definitely will fix your issue. I forgot to include one change when modifying my fork from my local version. Sorry, hopefully this will work
