### ISSUE TITLE
vorp_crafting crashing when create new character 

### ISSUE THREAD

**Issue by xthosad** [VORPCORE/vorp_crafting#9]
Hi, I'm using the last version of vorp premade server and there is a conflict of vorp_crafting and character creation
New players can not create a character, when I try to create a character I get thrown out of the character creation menu.

**Comment by xthosad** [comment]
![unknown](https://user-images.githubusercontent.com/83423742/180505930-ddad23c8-f10c-4948-8b21-60cde21a1e17.png)

**Comment by AndrewR3K** [comment]
Looking into this today

**Comment by AndrewR3K** [comment]
I have a potential PR up for this fix https://github.com/VORPCORE/vorp_crafting/pull/10
